### ISSUE TITLE
Weird extra drag line at extreme right of page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#152]
@coolshaurya commented on [Wed Jun 06 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17458)

This weird extra drag line appears at the extreme right of  the page. It can be confused with the console drag line which changes the width of the console. When dragging this line , it fills the console with errors - <br>
![image](https://user-images.githubusercontent.com/32027323/41031171-a756cf50-699d-11e8-9625-b2dc4be5914b.png)

#### Browser and operating system -

* Browser Name:  Google Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10 Fall Creators Update

#### Screenshot - 
![2018-06-06 15_17_00-window](https://user-images.githubusercontent.com/32027323/41031414-30ee303c-699e-11e8-8979-7041949f06ab.png)

![image](https://user-images.githubusercontent.com/32027323/41030501-1c871246-699c-11e8-8d2d-4b625421b62d.png)

**Comment by Bouncey** [comment]
@scissorsneedfoodtoo, any ideas?

**Comment by huyenltnguyen** [comment]
@Bouncey This splitter is the one between the editors and the preview pane. Because we don't conditionally render it, it's still there and gets pushed to the right when the preview pane is null.
I will submit a PR shortly.

https://github.com/freeCodeCamp/learn/blob/03c7a76fb7e40ec4ad6f6a1eea9fe4af2fbc719c/src/templates/Challenges/classic/Show.js#L229-L237

**Comment by scissorsneedfoodtoo** [comment]
@huyenltnguyen, thank you for taking this on! I think that's exactly what's going on. Let us know if you run into any problems and I'll be happy to QA your PR when it's ready.
