### ISSUE TITLE
Feature request: Save progress when tests pass, not when navigating to next challenge

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#154]
@forkerino commented on [Tue Jun 05 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17447)

#### Describe your problem and - if possible - how to reproduce it
I noticed some new exercises in sections for which I already solved most. Through the curriculum I opened one and did the exercise. When tests pass and I don't do ctrl-enter to go to the next or click on the green button, the exercise is still unfinished when I go to the curriculum. 

#### Add a Link to the page with the problem
All challenges

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: latest
* Operating System: Ubuntu 18.04

**Comment by tchaffee** [comment]
@raisedadead I would be happy to give this a try, but I might need some help from @Bouncey to understand where to look to even begin. Can you assign this to me if that's ok?

**Comment by tchaffee** [comment]
@raisedadead I'm blocked now because I can't authenticate in a test env. Any progress on #105? An idea on an ETA for that? I can also try to help you with that if you need a hand.

**Comment by tchaffee** [comment]
I was able to get the auth0.com workaround working so I can move forward with this. I noticed the modal says "Submit and go to next challenge..." implying the solution is not submitted until the button is clicked, which is accurate. Should the button text be changed to just "Go to next challenge" now that we will be saving progress when the tests pass?

![selection_151](https://user-images.githubusercontent.com/148813/42776482-83a033fa-890d-11e8-8c23-9ace53b706a1.png)

**Comment by tchaffee** [comment]
I started looking into this, and the code is pretty complex. I'm pretty sure I need to learn at least a couple of things to understand it. I'm currently learning RxJS. @Bouncey is there anything else I should look at besides RxJS and Redux in order to understand the code related to both the ToolPanel and the Completion Modal?
 
The Completion Modal is where the user submits the challenge and goes to the next challenge.
The Tool Panel is where the user clicks "Run Tests". 

So I'm trying to move the logic that saves the completed challenge from the Completion modal to the Tool Panel, if the tests succesfully complete. Here's the related code I've been able to find so far:

https://github.com/freeCodeCamp/learn/blob/master/src/templates/Challenges/components/Tool-Panel.js
https://github.com/freeCodeCamp/learn/blob/master/src/templates/Challenges/redux/execute-challenge-epic.js

https://github.com/freeCodeCamp/learn/blob/master/src/templates/Challenges/components/CompletionModal.js
https://github.com/freeCodeCamp/learn/blob/master/src/templates/Challenges/redux/completion-epic.js

https://github.com/freeCodeCamp/learn/blob/master/src/templates/Challenges/redux/index.js

**Comment by tchaffee** [comment]
@raisedadead I'm starting to roughly understand what needs to be done to change the epics and redux actions to make this happen. And I'm starting to question if it's actually a good idea in terms of user experience.

The current UX is:

1. Code
1. Run tests and tests fail
1. Code some more
1. Run tests and tests pass. 
1. Yeah! Modal appears.
1. User presses "Submit"
1. Solution is saved.
1. Route to next challenge.

The edge case is:
1. User presses "Cancel" or closes dialog.
1. Solution is NOT saved.

And I'm wondering if that's actually a bad UX. The user did something other than the usual flow. And we want to encourage the users to move fast and keep going from one challenge to the next. The reward for moving forward is that your solution is submitted.

Here's the new suggested UX:

1. Code
1. Run tests and tests fail
1. Code some more
1. Run tests and tests pass. 
1. Solution is automatically saved.
1. Yeah! Modal appears.
1. User presses "Go to Next Challenge"
1. Route to next challenge.

The edge case is:
1. User presses "Cancel" or closes dialog.
1. Solution has already been saved. Nothing else happens.

This feels just a little surprising to me. We are saving the solution as a side effect of pressing the "Run Tests" button. And there's nothing that would make me expect that a "Run Tests" button would save my solution when the tests pass.

I'm not super opinionated about this. I just want to discuss it as a team to make sure this is really what we want before moving ahead with it, as the change will take a lot of thinking and work on my side.

And while we are here, I'm wondering why folks close that dialog in the first place. I know why I do. I want to have a closer look at my code and a closer look at the results in the output iframe. Maybe we should take a closer look at the overall UX of testing, reviewing, fixing, and submitting the solution.

Maybe the modal itself is causing these UX problems? Ideally it should be super clear to the user when their solution is saved, and to even give them the ability to not save the solution. Right now it's a bit murky and a bit clumsy. And by saving the solution as a side effect of running tests it becomes even murkier and gives the user less control. Let's discuss.

**Comment by tchaffee** [comment]
As a set of user stories it might go like this:

1. I should be able to enter or change code and run tests.
1. I should be able to see which tests pass and which fail. DONE.
1. I should be able to submit / save code that passes all the tests. DONE.
1. I should be able to see when my solution has been saved and when it has not been saved. NOT DONE.
1. I should be able to move to the next challenge if all tests have passed. DONE.
1. I should be able to review my work and see the results after the tests pass. NOT DONE.

Please feel free to add / modify / make suggestions. I'm just brainstorming.
