### ISSUE TITLE
Terrible JavaScript syntax highlighting

### ISSUE THREAD

**Issue by coolshaurya** [freeCodeCamp/learn#227]
Here's how JS syntax highlighting currently looks in freeCodeCamp -
![image](https://user-images.githubusercontent.com/32027323/42417161-17bab93a-82a0-11e8-8cc1-1ae13c17ba87.png)

The massive blobs of white text are clearly visible and this makes it very difficult to see the code clearly.

Here's how the same code looks in VSCode -
![image](https://user-images.githubusercontent.com/32027323/42417188-d242d256-82a0-11e8-96ca-a71fd5e7d571.png)

Using the default VSCode dark theme -
![image](https://user-images.githubusercontent.com/32027323/42417213-a6df1312-82a1-11e8-813a-904bed3931b0.png)

BTW, Good work on making the dark theme work on the challenge pages.

**Comment by ValeraS** [comment]
It can be made something like this:
![image](https://user-images.githubusercontent.com/10867286/42474789-509d1f90-83d1-11e8-81cf-9dc4ddd58681.png)

Is it better?

**Comment by johnkennedy9147** [comment]
Looks like we are using themes Visual Studio (vs) and Visual Studio dark (vs-dark) which have poor syntax highlighting in comparison to the default themes used on VSCode which are Dark+ and Light+

The monaco editor only has light, dark and high contrast themes by default, but I think it is possible to extend these built-in themes.

I am looking at how to implement this and will try and implement the Dark+ and Light+ themes as used on VSCode.

**Comment by johnkennedy9147** [comment]
There is some scope for an improvement in the syntax highlighting, but implementing the full syntax highlighting seen in VSCode is not simple.

This is because the method used for theming is different. VSCode uses TextMate grammars which allows sophisticated tokenisation.
Monaco cannot use these (see image below of note on monaco repo) so is limited to the inbuilt js tokenisation unless we want to build a Monarch tokeniser with greater specificity. This is do-able but at the moment I dont think the improvement is worth the effort required.

![image](https://user-images.githubusercontent.com/26827682/42541123-1564bf00-8499-11e8-9dc8-b2b8c5fcb66f.png)

Before I spend more time on this I wanted to get your opinions @Bouncey @raisedadead @QuincyLarson 

Do you think it is desirable to have a custom theme which adds colourisation to any of these?
`(` and `)`
`[` and `]`
`{` and `}`
identifiers
operators and punctuation - done together due to implementation

Existing colourisation would be unaffected (or could be customised)

If we want to proceed what colours for each element for both light and dark themes?

**Comment by coolshaurya** [comment]
@ValeraS that would certainly improve the current situation although it is not a complete fix

**Comment by raisedadead** [comment]
I have always liked the Dracula color schemes for syntax highlighting in particular for the dark themes, maybe its worth adding a custom theme. I am all in for adding a theme that is that is based off of it. That said it should have to be an extension on top off monaco and NOT a CSS only update.

**Comment by coolshaurya** [comment]
The monarch tokenizer page on the monaco editor page should help - https://microsoft.github.io/monaco-editor/monarch.html

**Comment by raisedadead** [comment]
Hi @johnkennedy9147 

Thanks for taking the time to investigate on these. I really like the progress so far. Buy honestly the best feedback can come from the users themselves, which we would get once this is out.

Also we would have to take a11y into account when choosing colors.

I would recommend if you could possible research on existing examples, then it would be great. For example I know codesandbox.io uses monaco.

**Comment by coolshaurya** [comment]
I think that the color scheme should be taken from a popular theme like Dracula or Cobalt2 which are already great.

**Comment by johnkennedy9147** [comment]
Unfortunately I won't be able to do any more on this for a while, probably into next year so I have removed my assignment and added help wanted label, anyone who feels able can pick this up.
I'll come back to it as a priority if it is still unresolved when I'm able to put more time in.
cc @raisedadead

**Comment by coolshaurya** [comment]
It shouldn't be a problem if we copy CodeSandbox's configuration because its licence states -
```
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License
```

And we can always credit CodeSandbox.

In fact, I think that we should copy all of [CodeSandbox's monaco config](https://github.com/CompuIves/codesandbox-client/tree/master/packages/app/src/app/components/CodeEditor/Monaco) ,which happens to be better than that of fCC[Giving proper credit].
