### ISSUE TITLE
Pane re-sizing allows you to shrink but not expand

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#49]
Challenge Name
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
Issue Description
There are several issues here (similar to the issue that already existed in Beta):

1) When shrinking and expanding the lesson pane => the editor size does not expand to the new pane size when expanding the lesson pane. No issue on expanding the lesson pane, adjusts accordingly
![image](https://user-images.githubusercontent.com/22984739/40242012-6dd83c22-5a8a-11e8-9e06-dda007a468b5.png)

2) Shirking the editor window is fine, expanding has several issues
a) does not allow you to expand the editor window, this green highlighted bar shows up
![image](https://user-images.githubusercontent.com/22984739/40242169-da66efd2-5a8a-11e8-9041-fdd9de4b145d.png)
b) to get the editor back, you need to re-size the lesson plan, then you can re-size the editor/preview pane
![image](https://user-images.githubusercontent.com/22984739/40242447-ba047560-5a8b-11e8-8fba-b8fca70d8f5e.png)

3) After attempting to expand the editor/preview pane which fails, if you move your cursor over the lesson pane ( no mouse button is clicked) the cusor changes to from arrow to expanding icon and it resizes the editor/preview pane and follows the mouse movement.

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

**Comment by beaucarnes** [comment]
I'm not sure if this is the same issue or not but I'll just put it here since it is similar. When I resize, the editor pane stays small. Also, on small window sizes, the error messages in the bottom right are hard to see. See gif for demonstration.
![fcc1](https://user-images.githubusercontent.com/1513130/40250607-c4316b1a-5aa4-11e8-8d51-f076151fa4d6.gif)

**Comment by scissorsneedfoodtoo** [comment]
@mstellaluna and @beaucarnes, I'm working on this now. Made some changes to both the editor and the output so that they expand and shrink horizontally when the browser window is resized. I'm currently working on a way to resize them vertically, and also resize horizontally/vertically when the panes resized, but the window size remains the same.

**Comment by Bouncey** [comment]
Closed via #82
