### ISSUE TITLE
Pane resizing Doesn't work properly.

### ISSUE THREAD

**Issue by Ujjwal1604** [freeCodeCamp/learn#97]
The resizing of the **Coding pane** and the **Viewer pane** doesn't work properly. Please fix this issue. Thanks.<br>
![pan resizing](https://user-images.githubusercontent.com/39334002/40533767-9d18b79a-5fb8-11e8-8a85-e62bc91e6a12.gif)

**Comment by scissorsneedfoodtoo** [comment]
@Ujjwal1604, great catch! Thank you for pointing this out.

I've been looking at this and the problem seems to be with how Firefox handles `<iframe>` elements. The panes resize correctly when I tested this on Chrome, but not on Firefox for some reason. I can try to dig more into this over the next couple of days.
